import worker from './worker_bundle.js';import fs from 'node:fs';
const P=[...JSON.parse(fs.readFileSync('/tmp/vcx_posts_zh.json','utf8')),...JSON.parse(fs.readFileSync('/tmp/vcx_posts_en.json','utf8'))].map(x=>({...x,content:x.content||'<p>Test</p>',excerpt:x.excerpt||'Test excerpt'}));let wf=P.find(x=>x.lang==='zh'&&x.path==='2026/07/05/worldfirst');wf.featured_media=999;wf.content='<p>Test</p><img src="/media/worldfirst.jpg" alt="">';
class S{constructor(s){this.s=s;this.a=[]}bind(...a){this.a=a;return this}async all(){let s=this.s,r=[];
if(s.includes('FROM pages'))r=this.a[0]==='about'?[{slug:'about',title:'关于',content:'<p>About</p>',path:'about'}]:[];
else if(s.includes('FROM categories'))r=[{id:7,name:'虚拟卡评测',slug:'virtual-credit-card',parent:0}];
else if(s.includes('FROM media'))r=(this.a[0]===999||this.a[0]==='media/worldfirst.jpg')?[{path:'media/worldfirst.jpg',alt:'WorldFirst',width:1200,height:675}]:[];
else if(s.includes('FROM posts')){r=[...P];if(/path\s*=\s*\?/i.test(s)){let ix=s.match(/SELECT id FROM posts WHERE path/) ? 0:0;r=r.filter(x=>x.path===this.a[ix]);}if(/lang\s*=\s*\?/i.test(s)){let lang=this.a.find(x=>x==='zh'||x==='en');if(lang)r=r.filter(x=>x.lang===lang);}if(s.includes('COUNT(*)'))return {results:[{n:r.length}]};r.sort((a,b)=>String(b.date).localeCompare(String(a.date)));let m=s.match(/LIMIT\s+(\d+)/i);if(m)r=r.slice(0,+m[1]);}
return {results:r}}}
const env={DB:{prepare:s=>new S(s)},R2:{get:async()=>null},API_TOKEN:'x'};async function get(p){let r=await worker.fetch(new Request('https://virtualcardx.com'+p),env,{}),t=await r.text(),m=t.match(/<script type="application\/ld\+json">(.*?)<\/script>/s);return {status:r.status,html:t,json:m?JSON.parse(m[1]):null}}
let home=await get('/'),page=await get('/about/'),cat=await get('/virtual-credit-card/'),art=await get('/2026/07/05/worldfirst/');let types=x=>(x.json?.['@graph']||[]).map(y=>y['@type']);let article=(art.json['@graph']||[]).find(x=>x['@type']==='Article');let out={home:types(home),page:types(page),category:types(cat),article:types(art),search:!!home.json['@graph'][0].potentialAction,article_image:article?.image,author:article?.author?.['@type'],logo:article?.publisher?.logo?.url,visible_breadcrumb:art.html.includes('class="breadcrumbs"'),author_link:art.html.includes('class="author-link"'),image_dims:/width="1200" height="675"/.test(art.html),image_alt:/src="\/media\/worldfirst\.jpg" alt="WorldFirst"/.test(art.html)};console.log(JSON.stringify(out,null,2));if(!out.home.includes('WebSite')||!out.home.includes('Organization')||!out.search||!out.page.includes('AboutPage')||!out.category.includes('CollectionPage')||!out.article.includes('Article')||!out.article.includes('BreadcrumbList')||out.author!=='Person'||!out.article_image?.length||!out.visible_breadcrumb||!out.author_link||!out.image_dims||!out.image_alt)process.exit(1);
