name = "vcx-new"
main = "index.js"
compatibility_date = "2025-04-30"
account_id = "ce642be238771f93eee372d5035c488d"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "vcx-db"
database_id = "d8d9395b-2580-41ba-8ce9-300b5754b42d"

[[r2_buckets]]
binding = "R2"
bucket_name = "vcx-media"
